### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by luoyjx** [dvajs/dva-gui#2]
![image](https://cloud.githubusercontent.com/assets/4217102/19211803/d7dd383e-8d77-11e6-88c7-59b0ee0c3640.png)

**Comment by luoyjx** [comment]
系统:win10
node: v4.3.0
npm:3.10.6

**Comment by sorrycc** [comment]
感谢关注，尚在开发中，目前还不可用。这个错误应该是用 `npm run build` 一下。
